spring:
  application:
    name: joy-church-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/joy
    username: ${DB_USERNAME:joy_user}
    password: ${DB_PASSWORD:your_password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_min_32_chars_your_jwt_secret_key}
  access-expiration: 1800000
  refresh-expiration: 604800000
  refresh-cookie-name: JOY_REFRESH_TOKEN

aws:
  s3:
    bucket: joy-church-files
    region: ap-northeast-2
