spring:
  application:
    name: joy-church-backend
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 32MB
  datasource:
    url: jdbc:postgresql://localhost:5432/joy
    username: ${DB_USERNAME:joy_user}
    password: ${DB_PASSWORD:your_password}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_min_32_chars_your_jwt_secret_key}
  access-expiration: 1800000
  refresh-expiration: 7776000000
  refresh-cookie-name: JOY_REFRESH_TOKEN

aws:
  s3:
    bucket: joy-hill
    region: ap-northeast-2
